### ISSUE TITLE
关于train_backbone的问题

### ISSUE THREAD

**Issue by stillwaterman** [ljmiao/PENCIL#2]
你好，我想问一下train backbone为什么不用加了noise label的数据训练呢，虽然论文中的backbone train也没用noise label,但是我想这不符合实际情况，既然有了clean label为什么还用noise label去训练呢，不知道你的想法是什么？

**Comment by stillwaterman** [comment]
我用了noise label去训练backbone和你的结果一致

**Comment by sailist** [comment]
论文中应该是用了的，这个在论文源码里也能看出来（再吐槽一下论文源码不包括完整的流程）。论文里说的是 without noise handling，意思是没有处理噪音，不代表没有noisy label，也即只有一开始的和噪音标签一起的交叉熵损失，但因为大学习率，所以不会过拟合（这个思路感觉确实在意料之外，能想出来确实厉害）
